### ISSUE TITLE
Switch away from cufon fonts to standard fonts (perhaps using google webfonts)

### ISSUE THREAD

**Issue by rgrp** [okfn/opendataday.org#10]
Currently using cufon.js which isn't great (we get images for text). Specific font used is AvenirLTStd-Light afaict:

http://opendataday.org/js/comicsans.js

Suggest we switch to normal fonts (+ web fonts as necessary). Standard approach would be something like OpenSans (or PT Sans) plus, say, Antic Slab ...

**Comment by morchickit** [comment]
I am closing this since we are re-working the site anyway.
