### ISSUE TITLE
Logo needs to be changed but LocalSettings.php is not available

### ISSUE THREAD

**Issue by copystar** [okfn/opendataday.org#32]
In order to change the logo from the MediaWiki default, the LocalSettings.php needs to be changed as described here: http://www.mediawiki.org/wiki/Manual:FAQ#How_do_I_change_the_logo.3F

I took the existing logo on the OpenDataDay website and inverted the colours for the wiki if you'd like to use that: 
https://github.com/copystar/opendataday.org/commit/b3f586bf506b17902ab9d4374a89fee1f8afb5b9

Thank you!
![opendatalogoinvert](https://f.cloud.github.com/assets/879434/2022012/69062d0e-8847-11e3-9fc9-6c5d74041f05.png)

**Comment by morchickit** [comment]
Closing, we need to change the logo anyway (since we don't want it to have the word hackathon anymore). Thank you for helping here!
