### ISSUE TITLE
Can't access all items in sidebar

### ISSUE THREAD

**Issue by trickvi** [okfn/opendataday.org#36]
The sidebar position is fixed so when I scroll it follows me around. I can see by looking at the source code of the site that I'm missing out on three items in the list which I can't access because of this.

**Comment by morchickit** [comment]
@rgrp - If you have some times this week, can you help us to fix this?

**Comment by jalbertbowden** [comment]
what browser/os are you in? i can't replicate this in safari, chrome, or firefox in os x or chrome or firefox in ubuntu.

**Comment by morchickit** [comment]
That was closed with this - https://github.com/okfn/opendataday.org/pull/64
