### ISSUE TITLE
Link URLs in the map

### ISSUE THREAD

**Issue by martinszy** [okfn/opendataday.org#53]
In the map, make the URL for each event clickable, so I can access more directly to each city's event.

I think the fix should be in the file
js/map.js 

Adding in line 23

``` javascript
var linkedUrl = "<a href=\""+record.get("url")+"\"">"+record.get("url")+"</a>";
record.set("url",linkedUrl);
```

I can't test it so I don't know if it works. The risk is that it displays the html in text instead of showing the link, that depends on how does the leaflet plugin handle each record, so I hope someone more familiar to the code could continue this.

Thanks.

**Comment by harry-wood** [comment]
I put this as an issue before #37  ...but my fix didn't work for some reason

**Comment by morchickit** [comment]
Added to #97. Closing it here.
