### ISSUE TITLE
map is broken

### ISSUE THREAD

**Issue by clkao** [okfn/opendataday.org#66]
probably gdoc api changed and recline is getting recordCount = 0

**Comment by morchickit** [comment]
Someone keep messing with the table headers...I am fixing it every other
day now!

**Comment by jdgarrido** [comment]
fixed, i remove the blank row on gdoc and resolve the problem

**Comment by clkao** [comment]
well everything seems to be happening at (0,0) now! gotta book flights and yachts

**Comment by morchickit** [comment]
Fixed! 
Cell A1 needs to be named 'Place' and not 'location'. 
Also, for next year, it will be better if we will have a google form so people won't mess the map. 

Thanks guys for helping!
