### ISSUE TITLE
User Story #12: As a data activist I want an ODD that connects organically with grassroot efforts

### ISSUE THREAD

**Issue by offray** [okfn/opendataday.org#96]
One day events are a lot volatile and don't help the organic growth of communities. What we're doing is using this day as the last one of a recurrent longer one event called the [Data Week](https://discuss.okfn.org/t/data-week-7-our-critical-code-data-literacy-and-visualization-hackathon-returns/3823). How distributed events can raise connect communities and help them to grow organically?

**Comment by morchickit** [comment]
This is a good user story for the whole day, but not for the site as a whole. Can you please raise it in the Open Data Day mailing list as well?

**Comment by offray** [comment]
Thanks! Done. See:

https://discuss.okfn.org/t/user-story-12-as-a-data-activist-i-want-an-odd-that-connects-organically-with-grassroot-efforts/3954

Cheers,
